### ISSUE TITLE
How about provide a NER annotation example?

### ISSUE THREAD

**Issue by svjack** [CarperAI/cheese#28]
As the title said, can you give me some tips to implement a ner annotation example?

**Comment by LouisCastricato** [comment]
@shahbuland

**Comment by shahbuland** [comment]
> As the title said, can you give me some tips to implement a ner annotation example?

Do you mean something like highlighting text and then clicking a button to mark that the selection is a type of entity? Previously struggled to get text highlighting functionality like this out of gradio but I'll give it another go.

**Comment by shahbuland** [comment]
After further investigation, (see the new ner-example branch and the example contained within) this simply isn't possible with gradio at the moment. I've opened an issue on their repository as a feature request for this. There seems to be interest on their end of added it so it might be possible soon. Will update here when they update there.

**Comment by svjack** [comment]
> After further investigation, (see the new ner-example branch and the example contained within) this simply isn't possible with gradio at the moment. I've opened an issue on their repository as a feature request for this. There seems to be interest on their end of added it so it might be possible soon. Will update here when they update there.

When gradio burn, I try it and think it may be a good annotation tools for programmer with few backend knowledge. But 
it seems difficult to overcome its "only display" characteristics, do you have some ideas ?
