### ISSUE TITLE
device=0 leads to AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by aashay96** [CarperAI/cheese#44]
**Describe the bug**
device is preset to be GPU for instruct hf pipeline. Needs to be taken as input for line 61 and 29. Otherwise it leads to AssertionError: Torch not compiled with CUDA enabled

**To Reproduce**
Run instruct_hf_pipeline.py on a CPU system

**Expected behavior**

detect GPU or take as input the device

**Comment by LouisCastricato** [comment]
Thanks! Our engineers typically don't work weekends. I'll have this resolved Monday.

**Comment by shahbuland** [comment]
Think I've addressed in #46

**Comment by aashay96** [comment]
awesome! Thanks
