### ISSUE TITLE
`webdataset` not installed but required

### ISSUE THREAD

**Issue by gsarti** [CarperAI/cheese#45]
**Describe the bug**
The `webdataset` package needs to be manually installed in order to run examples.

**To Reproduce**
1. Follow the procedure described in [Getting Started with CHEESE](https://cheese1.readthedocs.io/en/latest/started.html)
2. When running `python -m cheese.examples.image_selection` the execution fails with the following error

```shell
Traceback (most recent call last):
  File "/home/user/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/conda/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/cheese/examples/image_selection.py", line 2, in <module>
    from cheese.pipeline.iterable_dataset import IterablePipeline, InvalidDataException
  File "/home/user/cheese/cheese/pipeline/iterable_dataset.py", line 4, in <module>
    import webdataset as wds
ModuleNotFoundError: No module named 'webdataset'
```

**Expected behavior**

The example script should run without further installations. `webdataset` should be included in the `requirements.txt` file.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by LouisCastricato** [comment]
@shahbuland

**Comment by shahbuland** [comment]
Ah that is a legacy import I forgot to remove. I uninstalled wds locally and ran scripts again and everything should be fine in #46
